import type { SerializedEditorState } from 'lexical'

export function getDocumentTemplates() {
	return [
		{
			id: 'empty',
			name: 'Empty Template',
			description: 'Start from a blank template.',
			document: EMPTY,
			charCount: 1,
			tags: [],
		},
		{
			id: 'basic-lease-agreement',
			name: 'Basic Lease Agreement',
			description: 'A simple lease agreement template.',
			document: BASIC,
			charCount: 3517,
			tags: ['LEASE_AGREEMENT'],
		},
	]
}

export const EMPTY = {
	root: {
		children: [
			{
				children: [],
				direction: 'ltr',
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
			},
		],
		direction: 'ltr',
		format: '',
		indent: 0,
		type: 'root',
		version: 1,
		textFormat: 1,
	},
} as unknown as SerializedEditorState

export const BASIC = {
	root: {
		children: [
			{
				children: [
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Ref: ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: '#ApplicationCode',
						type: 'hashtag',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 1,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 1,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'This Tenancy Agreement',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ' is made on ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#AgreementDate',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ', between:',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 1,
				textStyle: '',
			},
			{
				children: [
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: '#LandlordName',
								type: 'hashtag',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: ' of ',
								type: 'text',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: '#PropertyAddress',
								type: 'hashtag',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: ' (hereinafter referred to as the ',
								type: 'text',
								version: 1,
							},
							{
								detail: 0,
								format: 2,
								mode: 'normal',
								style: '',
								text: 'Landlord',
								type: 'text',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: '),',
								type: 'text',
								version: 1,
							},
							{
								type: 'linebreak',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'and',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: '#TenantName',
								type: 'hashtag',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: ' of ',
								type: 'text',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: '#TenantAddress',
								type: 'hashtag',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: ' (hereinafter referred to as the ',
								type: 'text',
								version: 1,
							},
							{
								detail: 0,
								format: 2,
								mode: 'normal',
								style: '',
								text: 'Tenant',
								type: 'text',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: ').',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 2,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'list',
				version: 1,
				listType: 'number',
				start: 1,
				tag: 'ol',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'Collectively referred to as ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 2,
						mode: 'normal',
						style: '',
						text: 'the Parties',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The Tenant is identified by ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#TenantIDType',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ' No. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#TenantIDNumber',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ', a national of ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#TenantNationality',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '1. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Property',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The Landlord hereby lets to the Tenant the premises known as ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#PropertyName',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ', located at ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#PropertyAddress',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ', being ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#UnitNumber',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ' (the ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 2,
						mode: 'normal',
						style: '',
						text: 'Property',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '), together with all fixtures, fittings, and furniture listed in the attached inventory (if any).',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '2. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Term',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The tenancy shall commence on ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#LeaseStartDate',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ' and shall continue for a period of ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#LeaseDuration',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ', ending on ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#LeaseEndDate',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ', unless renewed or terminated earlier in accordance with this Agreement.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '3. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Rent and Payment Terms',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The Tenant agrees to pay rent of ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'GHS ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#RentAmount',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: ' (',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#RentAmountInWords',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: ')',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ' per ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#RentFrequency',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ', payable in advance on or before the ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#PaymentDueDate',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ' of each period.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'Rent shall be paid by:',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'Bank transfer, mobile money, or any other method approved by the Landlord.',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'To the following account: ',
								type: 'text',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: '#PaymentAccountDetails',
								type: 'hashtag',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: '.',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 2,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'list',
				version: 1,
				listType: 'bullet',
				start: 1,
				tag: 'ul',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'A security deposit of ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#SecurityDeposit',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ' is payable prior to occupancy and shall be refundable at the end of the tenancy, less any lawful deductions for damage or unpaid utilities. An initial deposit of ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '#InitialDeposit',
						type: 'hashtag',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ' shall be paid upon execution of this Agreement.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '4. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Utilities',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The Tenant shall be responsible for payment of:',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'Electricity',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'Water',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 2,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'Internet and any other personal utilities',
								type: 'text',
								version: 1,
							},
							{
								type: 'linebreak',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'unless otherwise stated in Schedule A.',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 3,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'list',
				version: 1,
				listType: 'bullet',
				start: 1,
				tag: 'ul',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The Landlord shall ensure that all meters are in working order at the start of the tenancy.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '5. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Maintenance and Repairs',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The Tenant agrees to:',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'Keep the Property clean and in good condition.',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'Promptly notify the Landlord of any damage or need for repair.',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 2,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'Not make alterations or install fixtures without written consent.',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 3,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'list',
				version: 1,
				listType: 'bullet',
				start: 1,
				tag: 'ul',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The Landlord shall handle structural repairs, plumbing, and electrical faults not caused by the Tenant’s negligence.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '6. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Use of Property',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The Tenant shall:',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'Use the Property for residential purposes only.',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'Not engage in illegal or disruptive activities.',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 2,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'Not sublet or assign the premises without prior written consent.',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 3,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'list',
				version: 1,
				listType: 'bullet',
				start: 1,
				tag: 'ul',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '7. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Inspection and Access',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The Landlord or authorized agent may enter the Property for inspection, maintenance, or emergency repairs with at least ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: '24 hours’ notice',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ' to the Tenant.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '8. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Termination and Notice',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'Either party may terminate this Agreement by giving at least ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: "three (3) months'",
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ' written notice before the intended date of termination.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'Upon termination:',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'The Tenant shall vacate and return the Property in its original condition.',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: 'The Landlord shall refund the security deposit within ',
								type: 'text',
								version: 1,
							},
							{
								detail: 0,
								format: 1,
								mode: 'normal',
								style: '',
								text: 'thirty (30)',
								type: 'text',
								version: 1,
							},
							{
								detail: 0,
								format: 0,
								mode: 'normal',
								style: '',
								text: ' days after inspection, subject to deductions (if any).',
								type: 'text',
								version: 1,
							},
						],
						direction: null,
						format: '',
						indent: 0,
						type: 'listitem',
						version: 1,
						value: 2,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'list',
				version: 1,
				listType: 'bullet',
				start: 1,
				tag: 'ul',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '9. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Renewal and Extension',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'The Tenant may request a renewal or extension before the end date.',
						type: 'text',
						version: 1,
					},
					{
						type: 'linebreak',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'Any renewal shall be documented in writing and may include revised rent terms as mutually agreed.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '10. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Default and Breach',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'Failure by the Tenant to pay rent or comply with this Agreement may result in termination and eviction in accordance with Ghanaian law.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '11. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Governing Law',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: 'This Agreement shall be governed by and construed in accordance with the laws of the ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Republic of Ghana',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: ', particularly the ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 2,
						mode: 'normal',
						style: '',
						text: 'Rent Act, 1963 (Act 220)',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '.',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: 'normal',
						style: '',
						text: '12. ',
						type: 'text',
						version: 1,
					},
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Signatures',
						type: 'text',
						version: 1,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'heading',
				version: 1,
				tag: 'h3',
			},
			{
				children: [
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Landlord / Agent:',
						type: 'text',
						version: 1,
					},
					{
						type: 'linebreak',
						version: 1,
					},
					{
						type: 'signature',
						version: 1,
						role: 'property_manager',
						label: 'Property Manager',
						signatureUrl: null,
						signedByName: null,
						signedAt: null,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 1,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Tenant:',
						type: 'text',
						version: 1,
					},
					{
						type: 'linebreak',
						version: 1,
					},
					{
						type: 'signature',
						version: 1,
						role: 'tenant',
						label: 'Tenant',
						signatureUrl: null,
						signedByName: null,
						signedAt: null,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 1,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Witness (Landlord):',
						type: 'text',
						version: 1,
					},
					{
						type: 'linebreak',
						version: 1,
					},
					{
						type: 'signature',
						version: 1,
						role: 'pm_witness',
						label: 'Property Manager Witness',
						signatureUrl: null,
						signedByName: null,
						signedAt: null,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 1,
				textStyle: '',
			},
			{
				children: [
					{
						detail: 0,
						format: 1,
						mode: 'normal',
						style: '',
						text: 'Witness (Tenant):',
						type: 'text',
						version: 1,
					},
					{
						type: 'linebreak',
						version: 1,
					},
					{
						type: 'signature',
						version: 1,
						role: 'tenant_witness',
						label: 'Tenant Witness',
						signatureUrl: null,
						signedByName: null,
						signedAt: null,
					},
				],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 1,
				textStyle: '',
			},
			{
				children: [],
				direction: null,
				format: '',
				indent: 0,
				type: 'paragraph',
				version: 1,
				textFormat: 0,
				textStyle: '',
			},
		],
		direction: 'ltr',
		format: '',
		indent: 0,
		type: 'root',
		version: 1,
		textFormat: 1,
	},
} as unknown as SerializedEditorState
