// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://rentloop.com/terms",
        "contact": {
            "name": "Domey Benjamin",
            "url": "https://www.linkedin.com/in/benjamin-armah-kesey-domey/",
            "email": "domeybenjamin1@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admins": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all admins",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admins"
                ],
                "summary": "Get all admins",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "meta": {
                                            "$ref": "#/definitions/lib.HTTPReturnPaginatedMetaResponse"
                                        },
                                        "rows": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/transformations.OutputAdmin"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admins"
                ],
                "summary": "Create a new admin",
                "parameters": [
                    {
                        "description": "Admin details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/transformations.OutputAdmin"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admins/login": {
            "post": {
                "description": "Authenticate admin and return token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admins"
                ],
                "summary": "Authenticate admin and return token",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/transformations.OutputAdminWithToken"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admins/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the currently authenticated admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admins"
                ],
                "summary": "Get the currently authenticated admin",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/transformations.OutputAdmin"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admins/{admin_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get admin by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admins"
                ],
                "summary": "Get admin by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin ID",
                        "name": "admin_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/transformations.OutputAdmin"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/client-applications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all ClientApplications",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ClientApplications"
                ],
                "summary": "Get all ClientApplications",
                "parameters": [
                    {
                        "enum": [
                            "ClientApplication.Status.Pending",
                            "ClientApplication.Status.Approved",
                            "ClientApplication.Status.Rejected"
                        ],
                        "type": "string",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "LANDLORD",
                            "PROPERTY_MANAGER",
                            "DEVELOPER",
                            "AGENCY"
                        ],
                        "type": "string",
                        "name": "sub_type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "INDIVIDUAL",
                            "COMPANY"
                        ],
                        "type": "string",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "meta": {
                                            "$ref": "#/definitions/lib.HTTPReturnPaginatedMetaResponse"
                                        },
                                        "rows": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/transformations.OutputClientApplication"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/client-applications/{application_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get clientApplication by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ClientApplications"
                ],
                "summary": "Get clientApplication by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ClientApplication ID",
                        "name": "application_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/transformations.OutputClientApplication"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/client-applications/{application_id}/approve": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin approves a client's application after review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ClientApplications"
                ],
                "summary": "Approve a client application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client Application ID",
                        "name": "application_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/transformations.OutputClientApplication"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/client-applications/{application_id}/reject": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin rejects a client application with a reason",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ClientApplications"
                ],
                "summary": "Reject a client application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client Application ID",
                        "name": "application_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rejection reason",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RejectClientApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/transformations.OutputClientApplication"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/client-users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new client user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ClientUsers"
                ],
                "summary": "Creates new client user",
                "parameters": [
                    {
                        "description": "Create Client User Request Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateClientUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Client user created successfully",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/transformations.OutputClientUser"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error occured when creating a client user",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Invalid or absent authentication token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "An unexpected error occured",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/clients/apply": {
            "post": {
                "description": "Create a new client application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ClientApplications"
                ],
                "summary": "Create a new client application",
                "parameters": [
                    {
                        "description": "Client Application details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateClientApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/transformations.OutputClientApplication"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lib.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CreateAdminRequest": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                }
            }
        },
        "handlers.CreateClientApplicationRequest": {
            "type": "object",
            "required": [
                "address",
                "city",
                "contact_email",
                "contact_name",
                "contact_phone_number",
                "country",
                "date_of_birth",
                "latitude",
                "longitude",
                "name",
                "region",
                "sub_type",
                "type"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "contact_email": {
                    "type": "string"
                },
                "contact_name": {
                    "type": "string"
                },
                "contact_phone_number": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id_document_url": {
                    "type": "string"
                },
                "id_expiry": {
                    "type": "string"
                },
                "id_number": {
                    "type": "string"
                },
                "id_type": {
                    "type": "string",
                    "enum": [
                        "DRIVERS_LICENSE",
                        "PASSPORT",
                        "NATIONAL_ID"
                    ]
                },
                "latitude": {
                    "type": "number"
                },
                "logo_url": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "registration_number": {
                    "type": "string"
                },
                "sub_type": {
                    "description": "INDIVIDUAL = LANDLORD; COMPANY = PROPERTY_MANAGER | DEVELOPER | AGENCY",
                    "type": "string",
                    "enum": [
                        "LANDLORD",
                        "PROPERTY_MANAGER",
                        "DEVELOPER",
                        "AGENCY"
                    ]
                },
                "support_email": {
                    "type": "string"
                },
                "support_phone": {
                    "type": "string"
                },
                "type": {
                    "description": "INDIVIDUAL | COMPANY",
                    "type": "string",
                    "enum": [
                        "INDIVIDUAL",
                        "COMPANY"
                    ]
                },
                "website_url": {
                    "type": "string"
                }
            }
        },
        "handlers.CreateClientUserRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "phone",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "client-user@example.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "John Doe"
                },
                "phone": {
                    "type": "string",
                    "example": "+233281234569"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "ADMIN",
                        "STAFF"
                    ],
                    "example": "ADMIN"
                }
            }
        },
        "handlers.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 8,
                    "example": "strongpassword123"
                }
            }
        },
        "handlers.RejectClientApplicationRequest": {
            "type": "object",
            "required": [
                "reason"
            ],
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "lib.HTTPError": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "lib.HTTPReturnPaginatedMetaResponse": {
            "type": "object",
            "properties": {
                "has_next_page": {
                    "type": "boolean",
                    "example": true
                },
                "has_previous_page": {
                    "type": "boolean",
                    "example": false
                },
                "order": {
                    "type": "string",
                    "example": "desc"
                },
                "order_by": {
                    "type": "string",
                    "example": "created_at"
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "transformations.OutputAdmin": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "4fce5dc8-8114-4ab2-a94b-b4536c27f43b"
                },
                "name": {
                    "type": "string",
                    "example": "Admin Name"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                }
            }
        },
        "transformations.OutputAdminWithToken": {
            "type": "object",
            "properties": {
                "admin": {
                    "$ref": "#/definitions/transformations.OutputAdmin"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw"
                }
            }
        },
        "transformations.OutputClientApplication": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "company address or individual home address",
                    "type": "string",
                    "example": "21st Neon Street"
                },
                "approved_by_id": {
                    "type": "string",
                    "example": "S90092"
                },
                "city": {
                    "type": "string",
                    "example": "Accra"
                },
                "contact_email": {
                    "type": "string",
                    "example": "contact@email.com"
                },
                "contact_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "contact_phone_number": {
                    "type": "string",
                    "example": "01234567890"
                },
                "country": {
                    "type": "string",
                    "example": "Ghana"
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "date_of_birth": {
                    "description": "individual specific fields",
                    "type": "string",
                    "example": "2025-01-31"
                },
                "description": {
                    "type": "string",
                    "example": "Taking you to the next level!"
                },
                "id": {
                    "type": "string",
                    "example": "4fce5dc8-8114-4ab2-a94b-b4536c27f43b"
                },
                "id_document_url": {
                    "type": "string",
                    "example": "www.id-doc-url.com/id.pdf"
                },
                "id_expiry": {
                    "type": "string",
                    "example": "2040-12-31"
                },
                "id_number": {
                    "type": "string",
                    "example": "GHA-123-456-7890"
                },
                "id_type": {
                    "type": "string",
                    "example": "GHANACARD"
                },
                "latitude": {
                    "type": "number",
                    "example": 5.6037
                },
                "logo_url": {
                    "type": "string",
                    "example": "www.logo-url.com/logo.png"
                },
                "longitude": {
                    "type": "number",
                    "example": -0.187
                },
                "name": {
                    "type": "string",
                    "example": "Company Name"
                },
                "region": {
                    "type": "string",
                    "example": "Greater Accra"
                },
                "registration_number": {
                    "description": "company specific fields",
                    "type": "string",
                    "example": "GR1234567890"
                },
                "rejected_because": {
                    "type": "string",
                    "example": "No reason"
                },
                "rejected_by": {
                    "$ref": "#/definitions/transformations.OutputAdmin"
                },
                "rejected_by_id": {
                    "type": "string",
                    "example": "R234110"
                },
                "status": {
                    "type": "string",
                    "example": "ClientApplication.Status.Approved"
                },
                "sub_type": {
                    "type": "string",
                    "example": "ESTATE MANAGER"
                },
                "support_email": {
                    "type": "string",
                    "example": "support@email.com"
                },
                "support_phone": {
                    "type": "string",
                    "example": "+233 (0)12 345 6789"
                },
                "type": {
                    "type": "string",
                    "example": "COMPANY"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "website_url": {
                    "type": "string",
                    "example": "www.company-url.com"
                }
            }
        },
        "transformations.OutputClientUser": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "client-user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "4fce5dc8-8114-4ab2-a94b-b4536c27f43b"
                },
                "name": {
                    "type": "string",
                    "example": "Client User Name"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+233281234569"
                },
                "role": {
                    "type": "string",
                    "example": "STAFF"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "RentLoop API",
	Description:      "This is the RentLoop API documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
