name: Website CI

on:
  push:
    paths:
      - 'apps/website/**'
    branches:
      - main
      - prod
  pull_request:
    paths:
      - 'apps/website/**'

jobs:
  code-checks:
      name: ⬣ ESLint & ʦ TypeScript
      runs-on: ubuntu-latest
      
      steps:
        - name: ⬇️ Checkout repo
          uses: actions/checkout@v4
  
        - name: ⎔ Setup node
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'yarn'
            cache-dependency-path: 'apps/website/yarn.lock'
  
        - name: 📦 Cache node_modules
          id: cache-node-modules
          uses: actions/cache@v4
          with:
            path: apps/website/node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('apps/website/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-node-modules-

        - name: 📥 Download deps
          if: steps.cache-node-modules.outputs.cache-hit != 'true'
          run: yarn install --frozen-lockfile
          working-directory: apps/website
          
        - name: 🔬 Lint
          run: yarn lint:ci
          working-directory: apps/website

        - name: 🔎 Type check
          run: yarn types:check
          working-directory: apps/website