deploy-staging:
	fly deploy --config fly.staging.toml --remote-only --build-arg NODE_ENV=staging

deploy-production:
	fly deploy --config fly.production.toml --remote-only --build-arg NODE_ENV=production